from typing import Any

class DataFrame: ...

def to_datetime(x: Any, errors: str = ...) -> Any: ...
def to_numeric(x: Any, errors: str = ...) -> Any: ...
def notna(x: Any) -> bool: ...
def isna(x: Any) -> bool: ...

class Series: ...
