/**
 * Trading and Financial Terms Glossary
 * Beginner-friendly explanations of common trading terminology
 */

export interface GlossaryTerm {
  term: string;
  shortDefinition: string;
  longDefinition: string;
  example?: string;
  goodRange?: string;
}

export const TRADING_GLOSSARY: Record<string, GlossaryTerm> = {
  // Risk Metrics
  sharpeRatio: {
    term: 'Sharpe Ratio',
    shortDefinition: 'Measures how much return you get for the risk you take',
    longDefinition: 'The Sharpe Ratio shows how well your investments reward you for taking risk. A higher number means better risk-adjusted returns. It compares your returns to a "safe" investment like Treasury bonds.',
    example: 'A Sharpe Ratio of 1.5 means you earn 1.5% extra return for every 1% of risk.',
    goodRange: 'Above 1.0 is good, above 2.0 is excellent'
  },
  
  beta: {
    term: 'Beta',
    shortDefinition: 'Measures how much your portfolio moves compared to the overall market',
    longDefinition: 'Beta shows how volatile your investments are compared to the market. A beta of 1.0 means your portfolio moves exactly like the market. Higher than 1.0 means more volatile (riskier), lower means less volatile (more stable).',
    example: 'Beta of 1.5 means if the market goes up 10%, your portfolio typically goes up 15%.',
    goodRange: 'Below 1.0 is less risky, 1.0 is market average, above 1.0 is more aggressive'
  },
  
  alpha: {
    term: 'Alpha',
    shortDefinition: 'Extra returns beyond what the market provides',
    longDefinition: 'Alpha measures how much better (or worse) your portfolio performs compared to the overall market. Positive alpha means you\'re beating the market, negative alpha means you\'re underperforming.',
    example: 'An alpha of +3% means you earned 3% more than the market did.',
    goodRange: 'Any positive number is good, above 5% is excellent'
  },
  
  volatility: {
    term: 'Volatility',
    shortDefinition: 'How much and how quickly prices change',
    longDefinition: 'Volatility measures how much the price of an investment jumps around. High volatility means big price swings (riskier), low volatility means more stable prices (safer).',
    example: 'If a stock price varies by $10 daily, it has higher volatility than one that varies by $1.',
    goodRange: 'Lower is generally better for stability, but depends on your risk tolerance'
  },
  
  maxDrawdown: {
    term: 'Max Drawdown',
    shortDefinition: 'The biggest loss from peak to bottom',
    longDefinition: 'Maximum Drawdown shows the largest drop in value your portfolio experienced from its highest point to its lowest point. It helps you understand the worst-case loss you might face.',
    example: 'If your portfolio went from $10,000 to $8,000, the max drawdown is -20%.',
    goodRange: 'Smaller (less negative) is better. Under -10% is excellent'
  },
  
  sortinoRatio: {
    term: 'Sortino Ratio',
    shortDefinition: 'Like Sharpe Ratio, but only counts downside risk',
    longDefinition: 'The Sortino Ratio is similar to the Sharpe Ratio, but it only penalizes "bad" volatility (losses), not "good" volatility (gains). This gives a more realistic view of risk.',
    example: 'A Sortino of 2.0 means good returns relative to downside risk.',
    goodRange: 'Above 1.0 is good, above 2.0 is excellent'
  },
  
  vix: {
    term: 'VIX',
    shortDefinition: 'The "fear index" - measures expected market volatility',
    longDefinition: 'The VIX (Volatility Index) measures how much volatility investors expect in the next 30 days. High VIX means investors expect big price swings (uncertainty), low VIX means they expect stability.',
    example: 'VIX of 20 is normal, VIX of 30+ means high uncertainty/fear in markets.',
    goodRange: 'Below 20 is calm, 20-30 is moderate, above 30 is high uncertainty'
  },
  
  // Trading Concepts
  signal: {
    term: 'Trading Signal',
    shortDefinition: 'A recommendation to buy, sell, or hold a stock',
    longDefinition: 'A trading signal is generated by AI analysis and suggests whether you should buy, sell, or hold a particular stock. It includes a confidence score showing how strong the recommendation is.',
    example: 'Buy signal with 85% confidence means the AI strongly suggests purchasing.',
    goodRange: 'Confidence above 70% is generally considered strong'
  },
  
  portfolio: {
    term: 'Portfolio',
    shortDefinition: 'All your investments combined',
    longDefinition: 'Your portfolio is the complete collection of all your investments - stocks, bonds, cash, etc. It shows your total value, gains/losses, and how diversified you are.',
    example: 'A portfolio might contain 10 different stocks worth a total of $50,000.',
    goodRange: 'Diversified (many different investments) is generally better'
  },
  
  watchlist: {
    term: 'Watchlist',
    shortDefinition: 'Stocks you\'re monitoring but haven\'t bought yet',
    longDefinition: 'A watchlist is a list of stocks you\'re interested in tracking. You can monitor their prices, news, and signals without actually buying them yet.',
    example: 'You might watch AAPL and MSFT to decide if you want to buy them later.',
    goodRange: 'Keep it manageable - 5-20 stocks is typical'
  },
  
  sentiment: {
    term: 'Sentiment',
    shortDefinition: 'Overall feeling or mood about a stock (positive, negative, or neutral)',
    longDefinition: 'Sentiment analysis looks at news articles, social media, and other sources to determine if people feel positive, negative, or neutral about a stock. This can help predict price movements.',
    example: 'If most news is positive, sentiment is bullish (optimistic).',
    goodRange: 'Not a range - just positive, negative, or neutral'
  },
  
  // Position Types
  long: {
    term: 'Long Position',
    shortDefinition: 'Buying a stock hoping the price will go up',
    longDefinition: 'When you "go long" or take a long position, you buy a stock expecting its price to increase. You profit when you sell it for more than you paid.',
    example: 'Buy AAPL at $150, sell at $170 = $20 profit per share.',
    goodRange: 'N/A - this is just a strategy'
  },
  
  short: {
    term: 'Short Position',
    shortDefinition: 'Betting a stock price will go down',
    longDefinition: 'Shorting is an advanced strategy where you borrow shares, sell them, then buy them back cheaper to return them. You profit if the price drops. This is riskier than buying.',
    example: 'Borrow and sell AAPL at $150, buy back at $130, return shares = $20 profit.',
    goodRange: 'N/A - advanced strategy, not recommended for beginners'
  },
  
  // Market Terms
  quote: {
    term: 'Quote',
    shortDefinition: 'The current price of a stock',
    longDefinition: 'A quote shows the current bid (buy) and ask (sell) prices for a stock, along with the last traded price. It updates in real-time during market hours.',
    example: 'AAPL quote: $175.50 (last traded price)',
    goodRange: 'N/A - just current market information'
  },
  
  spread: {
    term: 'Spread',
    shortDefinition: 'Difference between buying and selling price',
    longDefinition: 'The spread is the gap between the bid (what buyers will pay) and ask (what sellers want). Smaller spreads mean more liquid (easier to trade) stocks.',
    example: 'Bid $100, Ask $100.10 = $0.10 spread',
    goodRange: 'Smaller is better - under $0.05 for liquid stocks'
  },
  
  volume: {
    term: 'Volume',
    shortDefinition: 'How many shares are being traded',
    longDefinition: 'Volume shows how many shares were bought and sold. High volume means lots of trading activity (more liquid), low volume means less activity (harder to trade).',
    example: '10 million shares traded today means high activity.',
    goodRange: 'Higher is generally better for ease of trading'
  },
  
  // Performance Metrics
  pnl: {
    term: 'P&L (Profit & Loss)',
    shortDefinition: 'How much money you made or lost',
    longDefinition: 'P&L shows your gains (profit) or losses. Realized P&L is from closed positions, unrealized P&L is from positions you still hold.',
    example: 'Bought at $100, now at $110 = +$10 unrealized P&L per share.',
    goodRange: 'Positive is good, but depends on your investment goals'
  },
  
  return: {
    term: 'Return',
    shortDefinition: 'The percentage gain or loss on an investment',
    longDefinition: 'Return shows how much you gained or lost as a percentage of your initial investment. It\'s the standard way to measure investment performance.',
    example: 'Invested $1,000, now worth $1,200 = 20% return.',
    goodRange: '7-10% annually is considered good for long-term investing'
  },
  
  // Risk Management
  diversification: {
    term: 'Diversification',
    shortDefinition: 'Spreading investments across different stocks to reduce risk',
    longDefinition: 'Diversification means not putting all your eggs in one basket. By investing in many different stocks, sectors, or asset types, you reduce the risk that one bad investment will hurt your whole portfolio.',
    example: 'Instead of 100% in one tech stock, own 10 different stocks in various industries.',
    goodRange: '15-30 different stocks is often recommended'
  },
  
  exposure: {
    term: 'Exposure',
    shortDefinition: 'How much money you have invested in something',
    longDefinition: 'Exposure shows what percentage of your portfolio is invested in a particular stock, sector, or asset type. Too much exposure to one area increases risk.',
    example: 'If 50% of your portfolio is tech stocks, you have high tech exposure.',
    goodRange: 'No single stock should be more than 10-20% of your portfolio'
  },
  
  // Order Types
  marketOrder: {
    term: 'Market Order',
    shortDefinition: 'Buy or sell immediately at the current price',
    longDefinition: 'A market order executes immediately at the best available current price. You\'re guaranteed to get the trade, but not guaranteed a specific price.',
    example: 'Market buy order for AAPL will buy at whatever price sellers are offering now.',
    goodRange: 'N/A - use for liquid stocks when price is less important than speed'
  },
  
  limitOrder: {
    term: 'Limit Order',
    shortDefinition: 'Buy or sell only at a specified price or better',
    longDefinition: 'A limit order only executes at your specified price or better. You control the price, but the order might not fill if the market doesn\'t reach your price.',
    example: 'Limit buy at $100 will only buy if price drops to $100 or below.',
    goodRange: 'N/A - use when you want price control over speed'
  }
};

/**
 * Get explanation for a trading term
 */
export function getTermExplanation(termKey: string): GlossaryTerm | undefined {
  return TRADING_GLOSSARY[termKey];
}

/**
 * Get short tooltip text for a term
 */
export function getTermTooltip(termKey: string): string {
  const term = TRADING_GLOSSARY[termKey];
  if (!term) return '';
  
  let tooltip = term.longDefinition;
  if (term.goodRange) {
    tooltip += `\n\nGood range: ${term.goodRange}`;
  }
  if (term.example) {
    tooltip += `\n\nExample: ${term.example}`;
  }
  return tooltip;
}

/**
 * Search for terms by keyword
 */
export function searchGlossary(keyword: string): GlossaryTerm[] {
  const searchLower = keyword.toLowerCase();
  return Object.values(TRADING_GLOSSARY).filter(term =>
    term.term.toLowerCase().includes(searchLower) ||
    term.shortDefinition.toLowerCase().includes(searchLower) ||
    term.longDefinition.toLowerCase().includes(searchLower)
  );
}
